services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '3002:3002'
    env_file:
      - ./.env
    depends_on:
      - postgres # Backend chỉ chờ PostgreSQL sẵn sàng
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: cristthien
      POSTGRES_PASSWORD: Thien@123
      POSTGRES_DB: amazingdb
    ports:
      - '5432:5432'
    volumes:
      - amazing-be_postgres_data:/var/lib/postgresql/data

volumes:
  amazing-be_postgres_data:
    external: true
